import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#ffffff',
  '--slot4-page-text': '#000000',
  '--slot4-panel-bg': '#f4f4f4',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5f6368',
  '--slot4-soft-muted-text': '#8b8f94',
  '--slot4-accent': '#fe4804',
  '--slot4-accent-fill': '#fe4804',
  '--slot4-accent-soft': '#fff0e8',
  '--slot4-green': '#8cff00',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#000000',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#f4f4f4',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#f4f4f4',
  '--slot4-lavender': '#ffffff',
  '--slot4-gray': '#f4f4f4',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#ffffff',
  '--editable-page-text': '#000000',
  '--editable-container': '80rem',
  '--editable-border': '#e6e6e6',
  '--editable-nav-bg': '#000000',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#fe4804',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#fe4804',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#000000',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-none',
  shadowStrong: 'shadow-[0_24px_70px_rgba(0,0,0,0.14)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-16',
    sectionY: 'py-16 sm:py-20 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[340px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-5xl font-medium leading-[0.96] sm:text-6xl lg:text-[3.875rem]',
    sectionTitle: 'text-3xl font-medium tracking-normal sm:text-5xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex h-[50px] items-center justify-center gap-2 bg-[var(--slot4-accent-fill)] px-8 text-sm font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:bg-[var(--slot4-page-text)] active:translate-y-0',
    secondary: 'inline-flex h-[50px] items-center justify-center gap-2 border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-8 text-sm font-medium text-[var(--slot4-page-text)] transition duration-300 hover:-translate-y-0.5 hover:border-[var(--slot4-page-text)] active:translate-y-0',
    accent: 'inline-flex h-[50px] items-center justify-center gap-2 bg-[var(--slot4-accent-fill)] px-8 text-sm font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:bg-[var(--slot4-page-text)] active:translate-y-0',
  },
  media: {
    frame: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(0,0,0,0.10)]',
    fade: 'transition duration-300 hover:opacity-70',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use SITE_CONFIG.name for the brand name.',
  'Public UI focuses on curated bookmarks, collections, and resources.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
